-- W4_GP_OuterJoins1_Archer.sql
-- Haley Archer

-- (14-1) Inner Join of TWOS and THREES
SELECT t.NUMBER_2, t.WORD_2, th.NUMBER_3, th.WORD_3 
FROM TWOS t 
INNER JOIN THREES th 
ON t.NUMBER_2 = th.NUMBER_3;

-- (14-2) Left, Right, and Full Outer Joins

-- Left Outer Join
SELECT t.NUMBER_2, t.WORD_2, th.NUMBER_3, th.WORD_3 
FROM TWOS t 
LEFT OUTER JOIN THREES th 
ON t.NUMBER_2 = th.NUMBER_3;

-- Right Outer Join
SELECT t.NUMBER_2, t.WORD_2, th.NUMBER_3, th.WORD_3 
FROM TWOS t 
RIGHT OUTER JOIN THREES th 
ON t.NUMBER_2 = th.NUMBER_3;

-- Full Outer Join
SELECT t.NUMBER_2, t.WORD_2, th.NUMBER_3, th.WORD_3 
FROM TWOS t 
FULL OUTER JOIN THREES th 
ON t.NUMBER_2 = th.NUMBER_3;

-- (14-3) Syntax for Left Outer Join
SELECT t.NUMBER_2, t.WORD_2, th.NUMBER_3, th.WORD_3 
FROM TWOS t 
LEFT OUTER JOIN THREES th 
ON t.NUMBER_2 = th.NUMBER_3;

-- (14-4) Syntax for Right Outer Join
SELECT t.NUMBER_2, t.WORD_2, th.NUMBER_3, th.WORD_3 
FROM TWOS t 
RIGHT OUTER JOIN THREES th 
ON t.NUMBER_2 = th.NUMBER_3;

-- (14-5) Syntax for Full Outer Join
SELECT t.NUMBER_2, t.WORD_2, th.NUMBER_3, th.WORD_3 
FROM TWOS t 
FULL OUTER JOIN THREES th 
ON t.NUMBER_2 = th.NUMBER_3;

-- (14-6) Writing a UNION in SQL
SELECT NUMBER_2 AS NUM, WORD_2 AS WORD FROM TWOS
UNION
SELECT NUMBER_3, WORD_3 FROM THREES;

-- (14-7) Creating TableC with UNION
CREATE TABLE TABLEC AS
SELECT NUMBER_2 AS NUM, WORD_2 AS WORD FROM TWOS
UNION
SELECT NUMBER_3, WORD_3 FROM THREES;

-- (14-8) Example of a SELECT with UNION
SELECT NUMBER_2, WORD_2 FROM TWOS
UNION
SELECT NUMBER_3, WORD_3 FROM THREES;
